[workspace]
resolver = "3"
members = ["crates/protocol", "crates/cli"]
exclude = ["reference/vote", "verifiers/ckb-context", "zk"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license = "MIT"
repository = "https://github.com/CellScript-Labs/AgoraSeal"
publish = false

[workspace.dependencies]
agoraseal-protocol = { path = "crates/protocol" }
ckb-gen-types = { version = "=1.1.1", default-features = false, features = ["calc-hash"] }
ckb-hash = { version = "=1.1.1", default-features = false, features = ["ckb-contract"] }
merkle-cbt = { version = "=0.3.2", default-features = false }

[profile.release]
overflow-checks = true
lto = "thin"
